name: Run Testing
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.5"
      - name: Install dependencies in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: pytest --cov=app --cov-fail-under=10
      - name: Run flake8 Linting
        run: |
          flake8 --extend-ignore E501 app/calculator/__init__.py app/operations/__init__.py main.py